name: MIG
favicon: null
layout_spectrum: 0.5200301462318748
typography_spectrum: 0.10547384340316057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7446394586004317
  lightness: 0.6881931605748832
  saturation: 0.2100692307576537
  rhythmicContrast: 0.7108488020021468
purpose: []
